name: github_graphql_client
description: Dart client for Github GraphQL
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  gql:
  gql_exec:
  gql_link:
  gql_http_link:
  http:
  oauth2:
  url_launcher:

dev_dependencies:
  build_runner:
  gql_build:
  pedantic:

flutter:
  uses-material-design: true
